const KEY="niwasaki.v1";
const state={stores:[],route:"home",selected:null,course:null,favoritesOnly:false};
const $=id=>document.getElementById(id); const now=()=>new Date().toISOString(); const uid=()=>Date.now()+"-"+Math.random().toString(36).slice(2,7); const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function load(){try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");state.stores=Array.isArray(v)?v:[]}catch{state.stores=[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.stores))}
function blank(){const t=now();return{id:"s_"+uid(),name:"",code:"",address:"",phone:"",course:"",deliveryPlace:"",entrance:"",parking:"",vehicleRoute:"",security:"",emptyCases:"",timeRestriction:"",notes:"",photos:[],favorite:false,createdAt:t,updatedAt:t}}
function courses(){return [...new Set(state.stores.map(s=>s.course).filter(Boolean))].sort()}
function go(route){state.route=route;state.selected=null;state.course=null;render();window.scrollTo({top:0,behavior:"smooth"})}
function shell(title,sub,body){$("app").innerHTML='<div class="page-head"><h1 class="page-title">'+title+'</h1>'+(sub?'<p class="page-sub">'+sub+"</p>":"")+'</div>'+body}
function empty(title,sub=""){return '<div class="empty"><strong>'+title+'</strong>'+(sub?'<span>'+sub+"</span>":"")+"</div>"}
function storeRow(s){return '<article class="store-row" data-id="'+s.id+'"><div class="thumb"></div><div><strong>'+esc(s.name||"名称未設定")+'</strong><small>'+esc(s.code||"コード未登録")+(s.course?"　"+esc(s.course):"")+'</small><small>'+esc(s.address||"住所未登録")+'</small></div><button class="star '+(s.favorite?"on":"")+'" data-fav="'+s.id+'">'+(s.favorite?"★":"☆")+"</button></article>"}
function bindRows(){document.querySelectorAll("[data-id]").forEach(e=>e.onclick=ev=>{if(ev.target.closest("[data-fav]"))return;state.selected=e.dataset.id;state.route="detail";render()});document.querySelectorAll("[data-fav]").forEach(e=>e.onclick=ev=>{ev.stopPropagation();const s=state.stores.find(x=>x.id===e.dataset.fav);if(s){s.favorite=!s.favorite;save();render()}})}
function home(){const fav=state.stores.filter(s=>s.favorite).slice(0,3);shell("ホーム","",'<button class="search-box" id="homeSearch"><span>⌕</span><input readonly placeholder="店舗名・コード・住所を検索"></button><div class="quick-list"><button class="quick-card" id="searchQuick"><span class="left"><span class="quick-icon">⌕</span><span><strong>店舗を探す</strong><small>名前・コード・住所から</small></span></span><span class="chevron">›</span></button><button class="quick-card" id="courseQuick"><span class="left"><span class="quick-icon">≡</span><span><strong>コースから探す</strong><small>コース別に店舗を見る</small></span></span><span class="chevron">›</span></button></div><section class="section"><div class="section-head"><h2>お気に入り</h2></div>'+(fav.length?'<div class="store-list">'+fav.map(storeRow).join("")+"</div>":empty("お気に入りはまだありません","店舗の☆から登録できます。"))+"</section><section class="section"><div class="section-head"><h2>最近見た店舗</h2></div>"+empty("最近見た店舗はまだありません")+"</section>');$("homeSearch").onclick=()=>go("search");$("searchQuick").onclick=()=>go("search");$("courseQuick").onclick=()=>go("courses");bindRows()}
function search(){shell("店舗を探す",state.stores.length+"件",'<div class="search-box"><span>⌕</span><input id="q" placeholder="店舗名・コード・住所で検索"></div><div class="section-head"><h2>店舗一覧</h2><button class="button secondary" id="newSearch">＋ 店舗登録</button></div><div id="results" class="store-list"></div>');const draw=()=>{const q=$("q").value.trim().toLowerCase();const list=state.stores.filter(s=>!q||[s.name,s.code,s.address,s.course].some(v=>String(v||"").toLowerCase().includes(q)));$("results").innerHTML=list.length?list.map(storeRow).join(""):empty("店舗がまだありません","「＋ 店舗登録」から追加できます。");bindRows()};$("q").oninput=draw;$("newSearch").onclick=()=>edit();draw()}
function coursesPage(){const cs=courses();shell("コースから探す","",cs.length?'<div class="course-list">'+cs.map(c=>'<button class="course-card" data-course="'+esc(c)+'"><span><strong>'+esc(c)+'</strong><small>'+state.stores.filter(s=>s.course===c).length+"店舗</small></span><span class="chevron">›</span></button>').join("")+"</div>":empty("コースがまだありません","店舗登録時にコースを設定できます。"));document.querySelectorAll("[data-course]").forEach(b=>b.onclick=()=>{state.course=b.dataset.course;const list=state.stores.filter(s=>s.course===state.course);$("app").innerHTML='<button class="back" id="courseBack">‹ コース一覧へ戻る</button><div class="page-head"><h1 class="page-title">'+esc(state.course)+'</h1></div><div class="store-list">'+list.map(storeRow).join("")+"</div>";$("courseBack").onclick=()=>coursesPage();bindRows()})}
function detail(){const s=state.stores.find(x=>x.id===state.selected);if(!s){go("search");return}const rows=[["コース",s.course],["納品場所",s.deliveryPlace],["搬入口",s.entrance],["駐車場所",s.parking],["車両進入経路",s.vehicleRoute],["鍵・警備",s.security],["空ケース等",s.emptyCases],["時間制限",s.timeRestriction],["注意事項",s.notes]].filter(x=>x[1]);$("app").innerHTML='<div class="detail"><button class="back" id="detailBack">‹ 店舗一覧へ戻る</button><div class="detail-head"><div><h1 class="detail-title">'+esc(s.name||"名称未設定")+'</h1><div class="meta">コード '+esc(s.code||"—")+'</div><div class="meta">'+esc(s.address||"住所未登録")+'</div>'+(s.phone?'<div class="meta">☎ '+esc(s.phone)+"</div>":"")+'</div><button class="star '+(s.favorite?"on":"")+'" id="detailFav">'+(s.favorite?"★":"☆")+'</button></div><div class="actions"><button class="button secondary" id="map">⌖ 地図を見る</button><button class="button primary" id="edit">情報を変更</button></div><div class="tabs"><button class="tab active" data-tab="delivery">配送情報</button><button class="tab" data-tab="photos">写真</button></div><div id="tabContent"><div class="info">'+(rows.length?rows.map(r=>'<div class="info-row"><b>'+r[0]+'</b><span>'+esc(r[1])+"</span></div>").join(""):empty("配送情報がありません"))+"</div></div></div>";$("detailBack").onclick=()=>go("search");$("detailFav").onclick=()=>{s.favorite=!s.favorite;save();render()};$("edit").onclick=()=>edit(s.id);$("map").onclick=()=>s.address&&window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(s.address),"_blank");document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("tabContent").innerHTML=b.dataset.tab==="photos"?(s.photos?.length?'<div class="photo-grid">'+s.photos.map(p=>'<img src="'+p+'" alt="">').join("")+"</div>":empty("写真がありません")):'<div class="info">'+(rows.length?rows.map(r=>'<div class="info-row"><b>'+r[0]+'</b><span>'+esc(r[1])+"</span></div>").join(""):empty("配送情報がありません"))+"</div>"})}
function field(k,label,s,full=false){return '<div class="field '+(full?"full":"")+'"><label>'+label+'</label>'+(full?'<textarea id="f_'+k+'">'+esc(s[k])+'</textarea>':'<input id="f_'+k+'" value="'+esc(s[k])+'">')+"</div>"}
function edit(id){const isNew=!id,s=id?state.stores.find(x=>x.id===id):blank();if(isNew)state.stores.push(s);$("app").innerHTML='<div class="detail"><button class="back" id="cancel">‹ 戻る</button><div class="page-head"><h1 class="page-title">'+(isNew?"店舗を登録":"情報を変更")+'</h1></div><form id="form"><section class="form-card"><h2>基本情報</h2><div class="form-grid">'+field("name","店舗名",s)+field("code","店舗コード",s)+field("address","住所",s)+field("phone","電話番号",s)+field("course","コース",s)+'</div></section><section class="form-card"><h2>配送情報</h2><div class="form-grid">'+field("deliveryPlace","納品場所",s)+field("entrance","搬入口",s)+field("parking","駐車場所",s)+field("vehicleRoute","車両進入経路",s)+field("security","鍵・警備",s)+field("emptyCases","空ケース等の置き場所",s)+field("timeRestriction","時間制限",s)+field("notes","注意事項",s,true)+'</div></section><div class="form-actions"><button class="button secondary" type="button" id="cancel2">キャンセル</button><button class="button primary">保存する</button></div></form></div>';const cancel=()=>{if(isNew){state.stores=state.stores.filter(x=>x.id!==s.id);save()}go("search")};$("cancel").onclick=cancel;$("cancel2").onclick=cancel;$("form").onsubmit=e=>{e.preventDefault();["name","code","address","phone","course","deliveryPlace","entrance","parking","vehicleRoute","security","emptyCases","timeRestriction","notes"].forEach(k=>s[k]=$("f_"+k).value.trim());s.updatedAt=now();save();state.selected=s.id;state.route="detail";render()}}
function render(){document.querySelectorAll("[data-route]").forEach(b=>b.classList.toggle("active",b.dataset.route===state.route));if(state.route==="home")home();else if(state.route==="search")search();else if(state.route==="courses")coursesPage();else if(state.route==="favorites"){state.favoritesOnly=true;const list=state.stores.filter(s=>s.favorite);shell("お気に入り",list.length+"件",list.length?'<div class="store-list">'+list.map(storeRow).join("")+"</div>":empty("お気に入りはまだありません"));bindRows()}else detail()}
function boot(){try{load();render()}catch(error){console.error(error);$("app").innerHTML='<div class="empty"><strong>niwasakiを起動できませんでした</strong><span>ページを再読み込みしてください。</span></div>'}}
document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>go(b.dataset.route));$("brand").onclick=()=>go("home");$("newStoreButton").onclick=()=>edit();$("adminButton").onclick=()=>alert("管理機能は次の実装段階で追加します。");boot();